### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by verdimrc**
*Issue #, if available:* N/A

*Description of changes:* beam search capability (PR #35)

*Testing done:* yes

## Merge Checklist

*Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're
unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of
what we are going to look for before merging your pull request.*

- [x] I have read the [CONTRIBUTING](https://github.com/awslabs/amazon-accessible-rl-sdk/blob/main/CONTRIBUTING.md) document.
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate).
- [x] I have updated any necessary documentation, including [README](https://github.com/awslabs/amazon-accessible-rl-sdk/blob/main/README.md) and [docs](https://github.com/awslabs/amazon-accessible-rl-sdk/tree/main/docs) (if appropriate).

By submitting this pull request, I confirm that my contribution is made under the terms of the
Apache 2.0 license.

### CODE REVIEW

**Comment by verdimrc** [comment]
@Laurenstc, @patrick22414: please review commit 76ce099 (fix mypy type error): whether tensor device & shape is still correct.

**Comment by songyiy22414** [comment]
hi @verdimrc 
- slightly modified the logic of `accum_logprobs` so that its type is always Tensor instead of Tensor | None, and also fit the name better
- fixed this in my test. `overwrite_valid_tokens` should've be a dict, somehow it was wrapped in a tuple
- `beam_search_n_steps()` is intended to input/output ndarray and only use tensors internally, as is what I found in other Simulator APIs. @yapweiyih please let me know if this is not the desired behaviour
  - fixed this naming [here](https://github.com/awslabs/amazon-accessible-rl-sdk/blob/9b0cf4a8a6ea6cdacc4bd15c1dd7a0ac620379f2/src/a2rl/simulator.py#L1350) where `seq_tensor` is cast back to ndarray which is also causing the mypy error

**Comment by verdimrc** [comment]
Hi @songyiy22414: would you like to push your changes to this branch, and let's see the CI/CD results?

**Comment by songyiy22414** [comment]
I don't have the clearance to push to public repos as per the company's open-source policy, so @Laurenstc has been helping me to push the changes. Apologies for the delay. We intend to push the changes and check the CI/CD results as soon as possible

**Review by Laurenstc — APPROVED** [review]
After linter & typing fixes LGTM.

**Pull request merged**
